# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce55b75826f2500660fb73b0e456e5526a5351d1822d615ee837af007469720f6300a8cd818b7da063bf0b292fd0a6d2bd24ea6f799f4fff9a210a573ba97853

test:
  secret_key_base: 2f0c9ffed845a59cd623d0ede1b9204e884fb8bdf5ea32d162d7731f5fb82421b072f5a67c73fe7c45dcc71358359bb17cc59e1da45a3b8101f4c8d902574c8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
